version: "3.7"

services:
    postgres:
        init: true
        build: "."
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./..:/workspace"
        ports:
            - "3000:3000"
            - "5432:5432"
        environment:
            - "DATABASE_URL=postgresql://postgres:me@localhost:5432/postgres"
            - "POSTGRES_PASSWORD=me"
